Neos:
  Flow:
    mvc:
      routes:
        'WebExcess.Comments':
          position: 'before Neos.Neos'
  Neos:
    fusion:
      autoInclude:
        WebExcess.Comments: true
    userInterface:
      translation:
        autoInclude:
          'WebExcess.Comments': ['Main', 'NodeTypes/*']
    nodeTypes:
      groups:
        comments:
          position: 100
          label: 'WebExcess.Comments:Main:nodeTypes.groups.comments'
          collapsed: false

  Fusion:
    defaultContext:
      Gravatar: 'WebExcess\Comments\Eel\Helper\GravatarHelper'

WebExcess:
  Comments:
    writeToDefaultDimension: false
    publishCommentsLive: true
    allowCommenting:
      account: true
      guest: true
    repliesDepth: 1
    form:
      preset: 'Bootstrap' # WebExcess | Bootstrap | Foundation | Material | Float